In [1]:
# import cleaned dataset 
import pandas as pd 
df = pd.read_csv(r"C:\Users\rahul\Desktop\AIRNB\data\processdata\listings_cleaned.csv")

Main Business Questions

Market Area 

Question 1- Which neighbourhoods have the most listings?

In [2]:

# Count listings for each neighbourhood 
neighbourhood_counts = (
    df["neighbourhood_cleansed"]
    .value_counts()  
)

# Display the top 10 neighbourhoods
print(neighbourhood_counts.head(10))

neighbourhood_cleansed
Bedford-Stuyvesant    2089
Midtown               1784
Williamsburg          1516
Harlem                1417
Hell's Kitchen        1365
Upper West Side       1194
Upper East Side       1187
Bushwick              1016
Crown Heights          876
Chelsea                733
Name: count, dtype: int64

Question 2- Which room types dominate?

In [3]:
# Count the number of listings for each room type 
room_type_counts =df[ 
    "room_type" ].value_counts()

# Display the count of listings for each room type 
room_type_counts

room_type
Entire home/apt    16808
Private room       12713
Hotel room           520
Shared room          218
Name: count, dtype: int64

In [4]:
# Calculate the percentage of listings for each room type 
room_type_percentage = df[
    "room_type" ].value_counts(normalize=True)*100

# Display the percentage of listings for each room type 
room_type_percentage

room_type
Entire home/apt    55.547110
Private room       42.013946
Hotel room          1.718497
Shared room         0.720447
Name: proportion, dtype: float64

Question 3- How is the market distributed geographically?

In [5]:
# Count listings in each neighbourhood 
most_listings_neighbourhood = (df
                               ["neighbourhood_cleansed"]
                               .value_counts()
                               )
print(most_listings_neighbourhood.head(10))

neighbourhood_cleansed
Bedford-Stuyvesant    2089
Midtown               1784
Williamsburg          1516
Harlem                1417
Hell's Kitchen        1365
Upper West Side       1194
Upper East Side       1187
Bushwick              1016
Crown Heights          876
Chelsea                733
Name: count, dtype: int64

Pricing Area 

Question 4 - What is the average price by neighbourhood and room type?

In [6]:
avg_price_listing = (
    df.groupby(["neighbourhood_cleansed","room_type"])
    ["price"]
    .mean()
    # .sort_values(ascending=True)
)

print(avg_price_listing.head(10))

neighbourhood_cleansed  room_type
Allerton                Entire home/apt    170.536087
                        Private room       132.825263
Arden Heights           Entire home/apt    145.063333
                        Private room       174.690000
Arrochar                Entire home/apt    176.808750
                        Private room       238.035000
Arverne                 Entire home/apt    294.957959
                        Private room       184.202667
                        Shared room        561.570000
Astoria                 Entire home/apt    230.746158
Name: price, dtype: float64

Question 5- Which areas are expensive?

In [7]:

# avg_price_listing =df["price"].mean()
# max_price_listing = (
#     df[df["price"]>avg_price_listing]
#     # .sort_values(ascending=True)
# )

# print(max_price_listing.head(10))


# Calculate average price
avg_price_listing = df["price"].mean()

# Filter listings where price is greater than average price
max_price_listing = df[
    df["price"] > avg_price_listing
][["neighbourhood_cleansed", "price"]]

# Sort prices from highest to lowest
max_price_listing = max_price_listing.sort_values(
    by="price",
    ascending=False
)
# Display first 10 listings
print(max_price_listing.head(10))

      neighbourhood_cleansed     price
29997                Tribeca  30972.96
22075        Upper East Side  14864.00
22076        Upper East Side  14864.00
798              Murray Hill  12279.07
731                  Midtown  12078.47
18011                Midtown  11061.80
18034                Midtown  11061.80
28452                Midtown  10986.00
28450                Midtown  10986.00
28451            Murray Hill  10986.00

Question 6- Are there unusual/extreme prices?

In [8]:
# Select area and price
price_data = df[["neighbourhood_cleansed", "price"]]

# Lowest 10
print("Lowest 10 Prices:")
print(price_data.sort_values(by="price").head(10))

# Highest 10
print("\nHighest 10 Prices:")
print(price_data.sort_values(by="price", ascending=False).head(10))

Lowest 10 Prices:
      neighbourhood_cleansed  price
15934                 Harlem   4.58
18314            Sunset Park   7.20
1688      Financial District   7.22
14174           Emerson Hill  10.23
23558        Upper East Side  10.45
13881                Chelsea  10.71
5397         Upper West Side  10.73
22893     Washington Heights  10.75
15542                Midtown  11.01
18464           Howard Beach  11.07

Highest 10 Prices:
      neighbourhood_cleansed     price
29997                Tribeca  30972.96
22076        Upper East Side  14864.00
22075        Upper East Side  14864.00
798              Murray Hill  12279.07
731                  Midtown  12078.47
18011                Midtown  11061.80
18034                Midtown  11061.80
28450                Midtown  10986.00
28451            Murray Hill  10986.00
28452                Midtown  10986.00

Hosts Area  

Question 7- Which hosts manage the most listings?

In [9]:
# Count the number of listings for each host
host_listings = (
    df.groupby(["host_id", "host_name"])
    .size()
    .sort_values(ascending=False) 
)
# Display the top 10 hosts with the most listings
print( host_listings.head(10))

host_id    host_name
107434423  Blueground             955
446820235  Luxury Bookings Fze    331
51501835   Jeniffer               262
19303369   Hiroki                 239
162280872  Urban Furnished        231
35491667   LEAP NY Apartments     217
476218709  Kristina               214
200239515  Shogo                  212
204704622  Momoyo                 205
137358866  Kaz                    157
dtype: int64

 Question 8-How common are multi-listing hosts?

In [10]:
# Count the number of hosts with only one listing
host_counts = (
    df.groupby(["host_id", "host_name"])
    .size()
    .sort_values(ascending=False)
)
# Print the count and percentage of hosts with only one listing
print("common multi-listing in count:",(host_counts == 1).sum())
print("common multi-listing in precentage:",(host_counts == 1).mean()*100)

common multi-listing in count: 13274
common multi-listing in precentage: 80.57545222775282

Question 9- Where are they concentrated?

In [11]:
# Find the neighbourhoods where multi-listing hosts are concentrated

multi_listing = df['neighbourhood_cleansed'].value_counts().head(10)

# Print the neighbourhoods with the most listings
print(multi_listing)

neighbourhood_cleansed
Bedford-Stuyvesant    2089
Midtown               1784
Williamsburg          1516
Harlem                1417
Hell's Kitchen        1365
Upper West Side       1194
Upper East Side       1187
Bushwick              1016
Crown Heights          876
Chelsea                733
Name: count, dtype: int64

Performance Area 

Question 10- Which listings receive the most reviews?

In [12]:
# Find the top-reviewed listings and sort them in descending order based on their number of reviews
top_reviewed = df[
    ["id",
     "host_name",
     "neighbourhood_cleansed",
     "number_of_reviews" ]
].sort_values(
    "number_of_reviews", 
    ascending=False )
# Display the top 10 reviewed listings
top_reviewed.head(10)

,id,host_name,neighbourhood_cleansed,number_of_reviews
18410,858697692672545141,Alfred,Chelsea,4502
15557,691676460109271194,SOBECA At SoHo Garden Hotel,Chinatown,2349
12559,51619634,Untitled,Lower East Side,2336
8768,37122502,The Ridge,East Village,2006
20172,992970965790772607,Candlewood Suites Times Square,Hell's Kitchen,1669
15698,700888293266225258,SOBECA At SoHo Garden Hotel,SoHo,1409
20485,1010503905929192028,Times Square South New York City,Hell's Kitchen,1376
4031,12171671,Alex & Zinaida,Chelsea,1327
13031,53132475,Untitled,Lower East Side,1262
8766,37122162,The Ridge,Lower East Side,1235

Question 11- Which neighbourhoods/room types have better ratings?

In [13]:
# Find the top-rated listings and sort them in descending order based on their review scores
top_rating = df[
    ["id",
     "host_name",
     "neighbourhood_cleansed",
     "room_type",
     "review_scores_rating" ]
].sort_values(
    "review_scores_rating", 
    ascending=False )

# Display the top 10 rated listings
top_rating.head(10)

,id,host_name,neighbourhood_cleansed,room_type,review_scores_rating
30180,1694378512267248596,Christy,Rockaway Beach,Private room,5.0
27,268481,Vishal,Williamsburg,Entire home/apt,5.0
26,268335,Herman,Williamsburg,Entire home/apt,5.0
30173,1694306596040411340,Ian,Bedford-Stuyvesant,Private room,5.0
30001,1685497282683086527,Mitesh,Theater District,Entire home/apt,5.0
29948,1700185373628753962,Eric,Financial District,Entire home/apt,5.0
29757,1682361523454976004,Brianna,Howard Beach,Private room,5.0
29679,1681920858958126735,Barbara,Flushing,Entire home/apt,5.0
29626,1679757208951712556,Idris,Bedford-Stuyvesant,Private room,5.0
29621,1679182208997974044,Mahbuba,Rosedale,Private room,5.0


Question 12- Is price related to ratings or reviews?

In [14]:
# Calculate average price, rating, and number of reviews
avg_price = df["price"].mean()
avg_rating = df["review_scores_rating"].mean()
avg_reviews = df["number_of_reviews"].mean()

# Print the averages of price, rating, and number of reviews
print("Average Price:", avg_price)
print("Average Rating:", avg_rating)
print("Average Reviews:", avg_reviews)

Average Price: 248.30950890644107
Average Rating: 4.768891569450412
Average Reviews: 32.40530090221091

Availability Area 

Question 13- Which areas and room types have high or low availability?

In [15]:
# Calculate the average occupancy across all listings
availability = (
    df.groupby(["neighbourhood_cleansed","room_type"])["estimated_occupancy_l365d"]
    .mean()
    .sort_values(ascending=False)
)

# Print the high and low availability listings
print("High availability:")
print(availability.head(10))  # High availability
print()
print("Low availability:")
print(availability.tail(10))   # Low availability

High availability:
neighbourhood_cleansed  room_type
Bay Ridge               Shared room        255.0
Tottenville             Private room       255.0
Sea Gate                Private room       255.0
Brownsville             Shared room        255.0
Fresh Meadows           Shared room        255.0
Huguenot                Private room       255.0
Harlem                  Hotel room         255.0
Greenpoint              Shared room        255.0
Graniteville            Entire home/apt    255.0
Maspeth                 Shared room        240.0
Name: estimated_occupancy_l365d, dtype: float64

Low availability:
neighbourhood_cleansed  room_type
Washington Heights      Shared room     0.0
Todt Hill               Private room    0.0
Tremont                 Private room    0.0
Woodrow                 Private room    0.0
Woodhaven               Shared room     0.0
Woodlawn                Private room    0.0
Co-op City              Private room    0.0
Arden Heights           Private room    0.0
Whitestone              Shared room     0.0
Woodside                Shared room     0.0
Name: estimated_occupancy_l365d, dtype: float64

Question 14- What does availability suggest about the market?

In [16]:
# Calculate the average occupancy across all listings
market_occupancy = df[
    "estimated_occupancy_l365d"
    ].mean()

# Print the average occupancy rounded to two decimal places
print("Average Occupancy:", round(market_occupancy, 2))

Average Occupancy: 52.43

Opportunity Area 

Question 15- If a new host enters the NYC market,
which neighbourhood/room type and price range could be worth
considering based on the analysis?

In [17]:
# Calculate the minimum, average, and maximum prices for each neighbourhood and room type for enters the market
result = (
    df.groupby(["neighbourhood_cleansed", "room_type"])
    ["price"]
      .agg(
          ["min", "mean", "max"])
      .reset_index()
)
# Print the results sorted by average price
print(result.sort_values("mean", ascending=True).head(10))

    neighbourhood_cleansed     room_type    min       mean     max
316    Morningside Heights   Shared room  27.13  27.130000   27.13
366            Port Morris   Shared room  31.39  31.390000   31.39
464     University Heights  Private room  40.43  40.790000   41.15
384              Rego Park   Shared room  42.33  42.330000   42.33
26                 Bayside   Shared room  42.48  42.480000   42.48
115                 Corona   Shared room  33.30  48.256000  105.60
98              Co-op City  Private room  39.47  52.233333   70.70
254        Jackson Heights   Shared room  45.57  53.520000   61.47
300                Maspeth   Shared room  55.33  55.330000   55.33
472        Upper West Side   Shared room  27.91  61.632500  373.15